<nav>
    <ul>
        <li><a href="index.php">Home</a></li>
        <li><a href="jobs.php">Jobs</a></li>
        <li><a href="apply.php">Apply</a></li>
        <li><a href="about.php">About</a></li>
        <li><a href="enhancements.php">Enhancements</a></li>
        <li><a href="enhancements2.php">Enhancements2</a></li>
        <li><a href="PHPenhancements.php">PHP Enhancements</a></li>
    </ul>
</nav>